stages:
  prepare:
    cmd: python ./Code/prepare.py ./Data/PMEmo2019/songs ./Data/PMEmo2019/songs_wav
    deps:
    - ./Code/prepare.py
    - ./Data/PMEmo2019/songs
    outs:
    - ./Data/PMEmo2019/songs_wav
  featurize:
    cmd: python ./Code/featurize.py ./Data/PMEmo2019/songs_wav ./Data/PMEmo2019/features/static_features.csv
    deps:
    - ./Code/featurize.py
    - ./Data/PMEmo2019/songs_wav
    outs:
    - ./Data/PMEmo2019/features/static_features.csv
  split_data:
    cmd: python ./Code/split_data.py ./Data/PMEmo2019/features/static_features.csv
      ./Data/PMEmo2019/annotations/static_annotations.csv
    deps:
    - ./Code/split_data.py
    - ./Data/PMEmo2019/annotations/static_annotations.csv
    - ./Data/PMEmo2019/features/static_features.csv
    outs:
    - ./Data/PMEmo2019/prepared/x_test.pkl
    - ./Data/PMEmo2019/prepared/x_train.pkl
    - ./Data/PMEmo2019/prepared/y_test.pkl
    - ./Data/PMEmo2019/prepared/y_train.pkl
  train:
    cmd: python ./Code/train.py
    deps:
    - ./Code/train.py
    - ./Data/PMEmo2019/prepared/x_test.pkl
    - ./Data/PMEmo2019/prepared/x_train.pkl
    - ./Data/PMEmo2019/prepared/y_test.pkl
    - ./Data/PMEmo2019/prepared/y_train.pkl
    params:
    - train.n_estimators
    - train.max_depth
    outs:
    - ./Modeling/model.pkl
  evaluate:
    cmd: python ./Code/evaluate.py ./Metrics/metrics.json
    deps:
    - ./Code/evaluate.py
    - ./Data/PMEmo2019/prepared/x_test.pkl
    - ./Data/PMEmo2019/prepared/y_test.pkl
    - ./Modeling/model.pkl
    metrics:
    - ./Metrics/metrics.json:
        cache: false
