train:
  vocab_size: 10000
  embedd_size: 100
  learning_rate: 0.001
  dropout: 0.1
  regularization_factor: 0.01
  hidden_units: [50, 64, 64, 32]
  batch_size: 10
  epochs: 1
  validation_split: 0.2
